In [1]:
#numpy позволяет эффективно проводить операции
import numpy as np


Одномерные массивы

In [9]:
a = [1, 2, 3]
b = np.array(a, dtype ='float64')
print(type(b),type(a))
b

<class 'numpy.ndarray'> <class 'list'>


array([1., 2., 3.])

In [10]:
#Если типы разные, то идет неявный каст к одному
a = [1, 2, 'a']
b = np.array(a)
print("Для list:", type(a[0]),
    "\n Для np.array:", type(b[0]))

Для list: <class 'int'> 
 Для np.array: <class 'numpy.str_'>


In [11]:
d = np.array([1, 2, 3,])
d
type(d)

numpy.ndarray

Методы класса ndarray

In [12]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',

In [14]:
#Узнаем размер массива
arr = np.array([5,6,2,1,10], dtype = 'int32')
arr.nbytes

20

In [20]:
#np.lookfor('mean value of array') #Поиск по деланию
?np.ma.mean 
#- Документация функции

Signature: np.ma.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
Docstring:
mean(self, axis=None, dtype=None, out=None, keepdims=<no value>)

Returns the average of the array elements along given axis.

Masked entries are ignored, and result elements which are not
finite will be masked.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.ndarray.mean : corresponding function for ndarrays
numpy.mean : Equivalent function
numpy.ma.average : Weighted average.

Examples
--------
>>> import numpy as np
>>> a = np.ma.array([1,2,3], mask=[False, False, True])
>>> a
masked_array(data=[1, 2, --],
             mask=[False, False,  True],
       fill_value=999999)
>>> a.mean()
1.5
File:      d:\miniconda\envs\ml\lib\site-packages\numpy\ma\core.py
Type:      function

In [21]:
np.con*?

np.concat
np.concatenate
np.conj
np.conjugate
np.convolve

In [22]:
#Количественные характеристики ndarray
arr = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
    ]
)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [26]:
print(
    "len:", len(arr),
    "\nsize:", arr.size,
    "\nndim:", arr.ndim,
    "\nshape:", arr.shape,
)

len: 4 
size: 16 
ndim: 2 
shape: (4, 4)


In [29]:
#Индексы
a=np.array([1,2,3,4])

a[0],a[1]

(np.int64(1), np.int64(2))

In [30]:
#last
a[-1]

np.int64(4)

In [31]:
a[2] = -1
a

array([ 1,  2, -1,  4])

#Использовать в циклах нежелательно, теряем преимущество быстродействия

In [32]:
for i in a:
    print(i)

1
2
-1
4


In [34]:
#Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер
a = np.array([2,3,5,7])
type(a), a.nbytes

(numpy.ndarray, 32)

Создание массивов


In [35]:
a = np.zeros(7) #массив из нулей
b = np.ones(7, dtype = np.int16) #единицы
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


In [ ]:
#Такой же массив как другой
c =np.zeros_like(b) #размер будет как у b и такой же тип данных
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [38]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [43]:
#функция np.arange подобна range
#фикс шаг
#правая граница не входит
a = np.arange(1,17,4)
print(a)
b = np.arange(5.,21,2)
print(b)
c = np.arange(1,10)
print(c)
print(np.arange(5))

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
#linspace - Начало и конец включается. Последовательности чисел с постоянным шагом. Последний аргумент - число точек
a = np.linspace(1,15,2)
b = np.linspace(5,12,10)
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


Создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [47]:
a = np.linspace(10,32,12)
print(a)
print(a[1]-a[0])

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


In [48]:
#Логарифмическая шкала от 10^0 до 10^3
b = np.logspace(0,3,12)
print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


2. Операции над одномерными массивами

In [49]:
#Вся арефметика производится поэлементно
a=np.linspace(3,33,11)
b=np.linspace(-2,-22,11)

print(a)
print(b)
print('\n\n')

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


In [50]:
#Один из операднов может быть скаляром
print(5*a)
print(10+b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [51]:
print((a+b)**2)
print(2**(a+b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [54]:
#Если типы элементов разные то идет каст к большему
print(a + np.arange(11, dtype ='int16'))
print(type(a[0])) #float - больше

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


In [ ]:
# в numpy есть элементарные функции - cos sin log exp ...
type(np.cos)

numpy.ufunc

In [56]:
np.log(b)

C:\Users\darkitime\AppData\Local\Temp\ipykernel_14048\4200754868.py:1: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [58]:
#Можно выполнять логические
print(a>b)
print(a==b)
print(a>=10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [65]:
#кванторы всеобщности и существования
c = np.arange(0.,20)
print(type(c[0]))

<class 'numpy.float64'>


In [66]:
np.any(c == 0.), np.all(c != 0.)

(np.True_, np.False_)

In [67]:
#Inplace операции
c += np.sin(4)
print(c)

[-0.7568025  0.2431975  1.2431975  2.2431975  3.2431975  4.2431975
  5.2431975  6.2431975  7.2431975  8.2431975  9.2431975 10.2431975
 11.2431975 12.2431975 13.2431975 14.2431975 15.2431975 16.2431975
 17.2431975 18.2431975]


In [68]:
#inplace только для операндов одинакового типа
c *= 2
print(c)

[-1.51360499  0.48639501  2.48639501  4.48639501  6.48639501  8.48639501
 10.48639501 12.48639501 14.48639501 16.48639501 18.48639501 20.48639501
 22.48639501 24.48639501 26.48639501 28.48639501 30.48639501 32.48639501
 34.48639501 36.48639501]


In [71]:
b = np.arange(1.,21,1)

d = (b+c)
d /= b
print(d)

[-0.51360499  1.2431975   1.82879834  2.12159875  2.297279    2.41439917
  2.49805643  2.56079938  2.60959945  2.6486395   2.68058136  2.70719958
  2.72972269  2.74902821  2.76575967  2.78039969  2.79331735  2.80479972
  2.81507342  2.82431975]


In [74]:
#При делени ndarray на 0, - исключения не бросается
print(np.array([0.0,0.0,1.0,-1.0]) / np.array([1.0,0.0,0.0,0.0]))

[  0.  nan  inf -inf]


C:\Users\darkitime\AppData\Local\Temp\ipykernel_14048\303800881.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0.0,0.0,1.0,-1.0]) / np.array([1.0,0.0,0.0,0.0]))
C:\Users\darkitime\AppData\Local\Temp\ipykernel_14048\303800881.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array([0.0,0.0,1.0,-1.0]) / np.array([1.0,0.0,0.0,0.0]))


In [75]:
#const
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [76]:
#cumsum
print(b)
print(b.cumsum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136. 153. 171. 190. 210.]


In [77]:
#sort
a = np.array([1,45,2])
print(np.sort(a))
print(a)

[ 1  2 45]
[ 1 45  2]


In [79]:
#method
a.sort()
print(a)

[ 1  2 45]


In [80]:
#Объединение
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [82]:
c = np.hstack((a,b,5*b))
c

array([ 1.,  2., 45.,  1.,  1.,  1.,  1.,  1.,  5.,  5.,  5.,  5.,  5.])

In [85]:
#Расщепление
x1,x2,x3,x4 = np.hsplit(c,[3,5,6])
print(c)
print(x1)
print(x2)
print(x3)
print(x4)

[ 1.  2. 45.  1.  1.  1.  1.  1.  5.  5.  5.  5.  5.]
[ 1.  2. 45.]
[1. 1.]
[1.]
[1. 1. 5. 5. 5. 5. 5.]


In [87]:
#функции append delete insert не inplace функции
print(np.delete(c,[2,4,1]))
print(c)

[1. 1. 1. 1. 1. 5. 5. 5. 5. 5.]
[ 1.  2. 45.  1.  1.  1.  1.  1.  5.  5.  5.  5.  5.]


In [88]:
np.insert(a,2,[-1,-1])

array([ 1,  2, -1, -1, 45])

In [89]:
np.append(a,[2.2,2.1])

array([ 1. ,  2. , 45. ,  2.2,  2.1])

In [90]:
#Индексирование и срезы
#обратный порядок
a[::-1]

array([45,  2,  1])

In [92]:
a = np.array([2,4,5,6,1,2,3,5,1])
print(a)

[2 4 5 6 1 2 3 5 1]


In [93]:
a[2:5:2]

array([5, 1])

In [ ]:
b = a[0:6]
b[1] = -1000
print(a)#меняется

[    2 -1000     5     6     1     2     3     5     1]


In [95]:
#Диапозоны с шагами
b=a[0:4:2]
print(b)
a[1:6:3]=0
print(a)

[2 5]
[2 0 5 6 0 2 3 5 1]


In [96]:
#copy
b=a.copy()
b[2] = -4
print(b)
print(a)

[ 2  0 -4  6  0  2  3  5  1]
[2 0 5 6 0 2 3 5 1]


In [97]:
print(a[[5,3,1]])#массив индексов

[2 6 0]


In [99]:
d = np.linspace(-4*np.pi,4*np.pi, 100)
print(d)

[-12.56637061 -12.31250454 -12.05863847 -11.8047724  -11.55090632
 -11.29704025 -11.04317418 -10.7893081  -10.53544203 -10.28157596
 -10.02770988  -9.77384381  -9.51997774  -9.26611167  -9.01224559
  -8.75837952  -8.50451345  -8.25064737  -7.9967813   -7.74291523
  -7.48904915  -7.23518308  -6.98131701  -6.72745093  -6.47358486
  -6.21971879  -5.96585272  -5.71198664  -5.45812057  -5.2042545
  -4.95038842  -4.69652235  -4.44265628  -4.1887902   -3.93492413
  -3.68105806  -3.42719199  -3.17332591  -2.91945984  -2.66559377
  -2.41172769  -2.15786162  -1.90399555  -1.65012947  -1.3962634
  -1.14239733  -0.88853126  -0.63466518  -0.38079911  -0.12693304
   0.12693304   0.38079911   0.63466518   0.88853126   1.14239733
   1.3962634    1.65012947   1.90399555   2.15786162   2.41172769
   2.66559377   2.91945984   3.17332591   3.42719199   3.68105806
   3.93492413   4.1887902    4.44265628   4.69652235   4.95038842
   5.2042545    5.45812057   5.71198664   5.96585272   6.21971879
   6.4735848

In [100]:
sum_cos_sin = np.sin(d)**2 + np.cos(d)**2
print(sum_cos_sin)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [101]:
np.all(d)

np.True_

3. Двумерные массивы

In [103]:
a = np.array([[1,2],[3,4]])
print(a)
a.ndim,a.shape,len(a),a.size

[[1 2]
 [3 4]]


(2, (2, 2), 2, 4)

In [104]:
#обращение по индексу
a[1][1], a[1,1]

(np.int64(4), np.int64(4))

In [110]:
b = np.arange(0,20)
print(b.reshape(2,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [111]:
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [112]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [113]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [114]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [115]:
d = np.diag(np.array([1,2,3,4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [123]:
e1 = np.diag(np.array([3**i for i in range(1,9)]))
print(e1)
e2=np.diag(np.array([-1 for i in range(1,9)]))
e2 = e2[::-1]
print(e2)
print(e1+e2)

[[   3    0    0    0    0    0    0    0]
 [   0    9    0    0    0    0    0    0]
 [   0    0   27    0    0    0    0    0]
 [   0    0    0   81    0    0    0    0]
 [   0    0    0    0  243    0    0    0]
 [   0    0    0    0    0  729    0    0]
 [   0    0    0    0    0    0 2187    0]
 [   0    0    0    0    0    0    0 6561]]
[[ 0  0  0  0  0  0  0 -1]
 [ 0  0  0  0  0  0 -1  0]
 [ 0  0  0  0  0 -1  0  0]
 [ 0  0  0  0 -1  0  0  0]
 [ 0  0  0 -1  0  0  0  0]
 [ 0  0 -1  0  0  0  0  0]
 [ 0 -1  0  0  0  0  0  0]
 [-1  0  0  0  0  0  0  0]]
[[   3    0    0    0    0    0    0   -1]
 [   0    9    0    0    0    0   -1    0]
 [   0    0   27    0    0   -1    0    0]
 [   0    0    0   81   -1    0    0    0]
 [   0    0    0   -1  243    0    0    0]
 [   0    0   -1    0    0  729    0    0]
 [   0   -1    0    0    0    0 2187    0]
 [  -1    0    0    0    0    0    0 6561]]


In [124]:
a = -1*np.eye(8)[::-1] + np.diag(np.arange(3,27,3))
print(a)

[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


In [126]:
a = 5*np.ones((5,5))
b = np.eye(5)+1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [128]:
print(a*b, '\n') #поэлементное умножение
print(a@b, '\n')
print(a.dot(b))

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [130]:
#двумерные массивы, зависящие только от одного индекса x_ij = uj, yij = vi
u = np.linspace(1,2,2)
v = np.linspace(4,8,3)
print(u)
print(v)

[1. 2.]
[4. 6. 8.]


In [131]:
x, y = np.meshgrid(u,v)
print(x,'\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


In [132]:
print(x.reshape(6))

[1. 2. 1. 2. 1. 2.]


In [136]:
#Отобразить вектор размера 100, в котором вычеркивается x, если x ---составное
is_prime = np.ones(100, dtype = bool)
is_prime[:2] = False

In [137]:
N_max = int(np.sqrt(len(is_prime)))
for i in range(2,N_max):
    is_prime[2*i::i] = False

print(is_prime)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]


In [138]:
#Маски
a = np.arange(20)
print(a%3 == 0)
print(a[a%3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


In [139]:
#trace
b = np.diag(a[a>=10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


In [141]:
#Тензоры
x = np.arange(64).reshape(8,2,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [142]:
x.shape, len(x), x.size, x.ndim

((8, 2, 4), 8, 64, 3)

In [146]:
#Суммы по разны
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(np.sum(x,axis=2))

[[224 232 240 248]
 [256 264 272 280]]
[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]]
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]]


In [149]:
print(np.sum(x,axis=(1,2)))
print(np.sum(x,axis=(0,1,2)))

[ 28  92 156 220 284 348 412 476]
2016


5. Линейная алгебра


In [151]:
a = np.array([[2,1],[2,3]])
print(a)

[[2 1]
 [2 3]]


In [ ]:
#det
np.linalg.det(a)

np.float64(4.0)

In [153]:
#a^-1
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [154]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [155]:
c = np.array ([[2,1],[6,3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
-3.330669073875464e-16


In [156]:
np.linalg.inv(c)

array([[-9.00719925e+15,  3.00239975e+15],
       [ 1.80143985e+16, -6.00479950e+15]])

In [158]:
#Решение НЛУ
v = np.array([5,-10])
print(np.linalg.solve(a,v))

print(b.dot(v))


[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


In [159]:
#С/в и с/з
l,u = np.linalg.eig(a)
print(l)
print(u)

[1.+0.j 4.+0.j]
[[-0.70710678+0.j -0.4472136 +0.j]
 [ 0.70710678+0.j -0.89442719+0.j]]


In [160]:
l,u = np.linalg.eig(a.T)
print(l)
print(u)

[1.+0.j 4.+0.j]
[[-0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j -0.70710678+0.j]]


In [162]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

[1.+0.j 1.+0.j 1.+0.j]
[[1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]]
